### PR TITLE
Fix license

### PR DESCRIPTION
**Pull request by mit-mit**
Align with the naming standard used by the Dart project elsewhere

### CODE REVIEW

**Comment by athomas** [comment]
This folder is following the guidelines outlines here:
https://github.com/docker-library/docs#files-related-to-an-images-docs

We already have https://github.com/dart-lang/dart-docker/blob/main/LICENSE at the top level and the whole `_docker-library` folder will be deleted when we're ready for to go official.

**Comment by mit-mit** [comment]
Ah, good catch. Yes, it's supposed to be a link to the "main software license" so changing to a link to our SDK license:

> This file should contain a link to the license for the main software in the image.

**Review by athomas — APPROVED** [review]
LGTM

**Comment by mit-mit** [comment]
@subfuzion OK to merge?

**Review by subfuzion — APPROVED** [review]
LGTM

**Review by subfuzion — APPROVED** [review]
LGTM

**Pull request merged**
