### PR TITLE
Add a docker build GitHub Actions workflow

### LINKED ISSUE #7: Add a CI test
Would be good to have some amount of CI testing.

For inspiration:
https://github.com/docker-library/golang/blob/master/.github/workflows/ci.yml

### PR DESCRIPTION
**Pull request by athomas**
Fixes #7.

### CODE REVIEW

**Comment by mit-mit** [comment]
Shouldn't we have at least some smoke-test to validate that the image is working (see also https://github.com/dart-lang/dart-docker/issues/7) ?

**Comment by athomas** [comment]
I'll see what happens if I use bashbrew instead.

**Comment by mit-mit** [comment]
Do we still need this @athomas ?

**Comment by athomas** [comment]
This is derived from https://github.com/docker-library/bashbrew/blob/master/scripts/github-actions/example-ci.yml.

**Review by jonasfj — APPROVED** [review]

**Pull request merged**
